<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-6Q9GTRJ" failures="1" tests="3" name="TestingWithEdge" time="13.577" errors="0" timestamp="2025-01-16T16:11:40 IST">
  <testcase classname="SeleniumJavaTestNGAssignment.TestScenarios" name="assign1_DOMElements" time="0.192">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [LambdaTest] but found [Selenium Grid Online | Run Selenium Test On Cloud]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [LambdaTest] but found [Selenium Grid Online | Run Selenium Test On Cloud]
at SeleniumJavaTestNGAssignment.TestScenarios.assign1_DOMElements(TestScenarios.java:42)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 19 stack frames]]>
    </failure>
  </testcase> <!-- assign1_DOMElements -->
  <testcase classname="SeleniumJavaTestNGAssignment.TestScenarios" name="assign2_CheckboxDemo" time="1.307"/>
  <testcase classname="SeleniumJavaTestNGAssignment.TestScenarios" name="assign3_JavascriptAlerts" time="1.074"/>
</testsuite> <!-- TestingWithEdge -->
